work around compile issues with duplicate symbols
Fixes following error:
arch/arm/mm/built-in.o:(___ksymtab+v7_dma_map_area+0x0): multiple definition of `__ksymtab_v7_dma_map_area'
arch/arm/kernel/built-in.o:(___ksymtab+v7_dma_map_area+0x0): first defined here
arch/arm/mm/built-in.o:(___ksymtab+v7_dma_flush_range+0x0): multiple definition of `__ksymtab_v7_dma_flush_range'
arch/arm/kernel/built-in.o:(___ksymtab+v7_dma_flush_range+0x0): first defined here
arch/arm/mm/built-in.o:(___ksymtab+v7_dma_unmap_area+0x0): multiple definition of `__ksymtab_v7_dma_unmap_area'
arch/arm/kernel/built-in.o:(___ksymtab+v7_dma_unmap_area+0x0): first defined here

Symbols are defined in arch/arm/mm/cache-v7.S and
arch/arm/kernel/setup.c